# -*- coding: utf-8 -*-
"""DM_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yR79nhYs6NR3iDwgWrHqYvdx4049FH_-

# Student Mental Health & Academic Risk Predictor
### Data Mining Project — CSL 460 | Bahria University Karachi Campus | BSE-6B | Spring 2026

---

| S. No. | Name | Enrollment # | Module |
|--------|------|--------------|--------|
| 01 | **M. Khizar Akram** *(Team Lead)* | 02-131232-064 | Module 4: App & Deployment |
| 02 | **Safwan Marwat** | 02-131232-051 | Module 1: Data Collection & EDA |
| 03 | **Syed Mughees** | 02-131232-017 | Module 2: Preprocessing & Feature Engineering |
| 04 | **Ifrahim Yousuf** | 02-131232-018 | Module 3: Model Training & Evaluation |

**Submitted to:** Dr. Hussain (Course Instructor) | Engr. Noor us Sabah (Lab Instructor)

---

## Project Overview
This project predicts the **academic risk level** (Low / Medium / High) of university students using self-reported lifestyle, psychological, and academic indicators. Four classification models are compared — Random Forest, SVM, XGBoost, and MLP — and the best-performing model is deployed via a Gradio web interface. SHAP values are used to explain individual predictions.

**Dataset:** Student Depression Dataset — Kaggle (~27,000 records, 27 features)  
**Platform:** Google Colab + Google Drive + Gradio (public shareable link)

## Environment Setup

> Run this cell first to install all required packages.
"""

!pip install xgboost shap gradio kaggle scikit-learn pandas numpy matplotlib seaborn -q
print("✅ All libraries installed successfully.")

"""---
## Module 1: Data Collection & Exploratory Data Analysis
**Responsible:** Safwan Marwat (02-131232-051)

This module handles:
1. Setting up the Kaggle API and downloading the Student Depression Dataset
2. Loading the dataset and inspecting its structure
3. Generating EDA visualizations — correlation heatmap, feature distributions, and class balance

### 1.1 — Kaggle API Setup & Dataset Download
"""

from google.colab import files

# Upload your kaggle.json credentials file
files.upload()

import os
os.makedirs(os.path.expanduser("~/.kaggle"), exist_ok=True)
os.system("cp kaggle.json ~/.kaggle/")
os.system("chmod 600 ~/.kaggle/kaggle.json")

# Download and extract the dataset
os.system("kaggle datasets download -d hopesb/student-depression-dataset -q")
os.system("unzip -o student-depression-dataset.zip -d .")
print("✅ Dataset downloaded and extracted.")

"""### 1.2 — Load Dataset & Initial Inspection"""

import pandas as pd
import numpy as np

raw_df = pd.read_csv('Student Depression Dataset.csv')

print(f"Dataset shape: {raw_df.shape}")
print(f"\nColumn names:\n{raw_df.columns.tolist()}")
print(f"\nData types:\n{raw_df.dtypes}")
print(f"\nMissing values per column:\n{raw_df.isnull().sum()}")
print(f"\nBasic statistics:")
raw_df.describe()

"""### 1.3 — Exploratory Data Analysis (EDA)"""

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

# Select the columns we'll use in the project
COLS_TO_KEEP = [
    'Gender', 'Age', 'Academic Pressure', 'CGPA',
    'Study Satisfaction', 'Sleep Duration', 'Dietary Habits',
    'Work/Study Hours', 'Financial Stress',
    'Family History of Mental Illness',
    'Have you ever had suicidal thoughts ?', 'Depression'
]
df_eda = raw_df[COLS_TO_KEEP].copy()

# ── 1. Correlation Heatmap (numerical columns only) ──────────────────────────
numerical_cols = ['Age', 'Academic Pressure', 'CGPA', 'Study Satisfaction',
                  'Work/Study Hours', 'Financial Stress', 'Depression']

plt.figure(figsize=(10, 7))
corr = df_eda[numerical_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap='coolwarm',
            vmin=-1, vmax=1, linewidths=0.5)
plt.title('Correlation Heatmap — Numerical Features', fontsize=14, pad=15)
plt.tight_layout()
plt.savefig('eda_correlation_heatmap.png', dpi=150)
plt.show()
print("→ Academic Pressure and Depression show a notably positive correlation.")

# ── 2. Distribution of Key Features ─────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(16, 8))
fig.suptitle('Distribution of Key Features', fontsize=14, y=1.01)

features_to_plot = {
    'CGPA': axes[0, 0],
    'Age': axes[0, 1],
    'Academic Pressure': axes[0, 2],
    'Work/Study Hours': axes[1, 0],
    'Financial Stress': axes[1, 1],
    'Study Satisfaction': axes[1, 2],
}

for feat, ax in features_to_plot.items():
    ax.hist(df_eda[feat].dropna(), bins=20, color='steelblue', edgecolor='white', alpha=0.85)
    ax.set_title(feat)
    ax.set_xlabel('Value')
    ax.set_ylabel('Count')

plt.tight_layout()
plt.savefig('eda_feature_distributions.png', dpi=150)
plt.show()

# ── 3. Categorical Feature Distributions ─────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
cat_features = ['Sleep Duration', 'Dietary Habits', 'Gender']
for ax, col in zip(axes, cat_features):
    df_eda[col].value_counts().plot(kind='bar', ax=ax, color='teal', edgecolor='white')
    ax.set_title(col)
    ax.set_xlabel('')
    ax.tick_params(axis='x', rotation=30)
plt.suptitle('Categorical Feature Distributions', fontsize=13)
plt.tight_layout()
plt.savefig('eda_categorical_features.png', dpi=150)
plt.show()

# ── 4. Depression Rate by Academic Pressure ───────────────────────────────────
plt.figure(figsize=(8, 4))
dep_by_pressure = df_eda.groupby('Academic Pressure')['Depression'].mean() * 100
dep_by_pressure.plot(kind='bar', color='salmon', edgecolor='white')
plt.title('Depression Rate (%) by Academic Pressure Level')
plt.xlabel('Academic Pressure (1=Low, 5=High)')
plt.ylabel('% Reporting Depression')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('eda_depression_by_pressure.png', dpi=150)
plt.show()

print("\n✅ EDA complete. All plots saved.")

"""---
## Module 2: Preprocessing & Feature Engineering
**Responsible:** Syed Mughees (02-131232-017)

This module handles:
1. Selecting and cleaning relevant features
2. Handling missing values (median for numerical, mode for categorical)
3. Label encoding categorical variables
4. Engineering the 3-class Risk Level target variable from the raw depression label
5. Feature scaling (StandardScaler) and saving artifacts to Google Drive

### 2.1 — Data Cleaning, Encoding & Risk Label Engineering
"""

import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from google.colab import drive

drive.mount('/content/drive')
print("✅ Google Drive mounted!")

# ── Load fresh dataset ────────────────────────────────────────────────────────
df = pd.read_csv('Student Depression Dataset.csv')

COLS_TO_KEEP = [
    'Gender', 'Age', 'Academic Pressure', 'CGPA',
    'Study Satisfaction', 'Sleep Duration', 'Dietary Habits',
    'Work/Study Hours', 'Financial Stress',
    'Family History of Mental Illness',
    'Have you ever had suicidal thoughts ?', 'Depression'
]
df = df[COLS_TO_KEEP].copy()

# ── Handle Missing Values ─────────────────────────────────────────────────────
print(f"Missing values before imputation:\n{df.isnull().sum()}\n")

for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print(f"Missing values after imputation: {df.isnull().sum().sum()} (all resolved)")

# ── Label Encode Categorical Variables ───────────────────────────────────────
CATEGORICAL_COLS = [
    'Gender', 'Sleep Duration', 'Dietary Habits',
    'Family History of Mental Illness',
    'Have you ever had suicidal thoughts ?'
]

encoders = {}
print("\nEncoding mappings:")
for col in CATEGORICAL_COLS:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le
    mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print(f"  {col}: {mapping}")

# ── Engineer 3-Class Risk Level Target ───────────────────────────────────────
def assign_risk(row):
    """
    Composite scoring function that maps raw dataset indicators
    to a 3-class academic risk level (Low=0, Medium=1, High=2).
    Designed by: Syed Mughees (Module 2)
    """
    score = 0
    # Risk factors (positive contributors)
    if row['Depression'] == 1:                           score += 3
    if row['Academic Pressure'] >= 4:                    score += 2
    if row['CGPA'] < 2.0:                                score += 2
    if row['Financial Stress'] >= 4:                     score += 1
    if row['Have you ever had suicidal thoughts ?'] == 1: score += 3
    # Sleep Duration: encoded 'Less than 5 hours' = 2 (LabelEncoder alphabetical)
    # Checking for the low-sleep encoded value
    if row['Sleep Duration'] == encoders['Sleep Duration'].transform(['Less than 5 hours'])[0]:
        score += 1
    # Protective factors (negative contributors)
    if row['CGPA'] >= 3.0:      score -= 2
    if row['Study Satisfaction'] >= 4: score -= 1

    if score <= 1:   return 0   # Low Risk
    elif score <= 4: return 1   # Medium Risk
    else:            return 2   # High Risk

df['Risk_Level'] = df.apply(assign_risk, axis=1)
df = df.drop(columns=['Depression'])

# ── Class Balance Chart ───────────────────────────────────────────────────────
class_counts = df['Risk_Level'].value_counts().sort_index()
class_labels = ['Low Risk', 'Medium Risk', 'High Risk']
colors = ['#2ecc71', '#f39c12', '#e74c3c']

plt.figure(figsize=(7, 4))
bars = plt.bar(class_labels, class_counts.values, color=colors, edgecolor='white', width=0.5)
for bar, count in zip(bars, class_counts.values):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 100,
             f'{count:,}\n({count/len(df)*100:.1f}%)',
             ha='center', va='bottom', fontsize=10)
plt.title('Class Distribution — Risk Level (Target Variable)', fontsize=13)
plt.ylabel('Number of Students')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/class_balance_chart.png', dpi=150)
plt.show()

print(f"\nClass distribution:\n{df['Risk_Level'].value_counts().sort_index()}")

# ── Feature Scaling ───────────────────────────────────────────────────────────
X = df.drop(columns=['Risk_Level'])
y = df['Risk_Level']
feature_names = X.columns.tolist()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(f"\nFeature names: {feature_names}")
print(f"X_scaled shape: {X_scaled.shape}")

# ── Save Preprocessing Artifacts ─────────────────────────────────────────────
with open('/content/drive/MyDrive/encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)
with open('/content/drive/MyDrive/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
with open('/content/drive/MyDrive/feature_names.pkl', 'wb') as f:
    pickle.dump(feature_names, f)

print("\n✅ All preprocessing artifacts saved to Google Drive.")

"""---
## Module 3: Model Training & Evaluation
**Responsible:** Ifrahim Yousuf (02-131232-018)

This module handles:
1. Stratified 80/20 train-test split
2. Training all four classifiers — Random Forest, SVM (RBF), XGBoost, MLP
3. GridSearchCV hyperparameter tuning for Random Forest and XGBoost
4. Evaluation with accuracy, precision, recall, F1-score (weighted), ROC-AUC, and 5-fold CV
5. Generating confusion matrices, ROC curves, and a side-by-side model comparison table

### 3.1 — Train-Test Split & Model Training with Hyperparameter Tuning
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import (train_test_split, cross_val_score,
                                      GridSearchCV, StratifiedKFold)
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix, ConfusionMatrixDisplay, roc_auc_score)

# ── Stratified Train/Test Split ───────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)
print(f"Train size: {X_train.shape[0]} | Test size: {X_test.shape[0]}")

# ── GridSearchCV Tuning for RF and XGBoost ────────────────────────────────────
print("\n⏳ Running GridSearchCV for Random Forest...")
rf_param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
}
rf_grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    rf_param_grid, cv=3, scoring='accuracy', n_jobs=-1, verbose=0
)
rf_grid.fit(X_train, y_train)
print(f"  Best RF params: {rf_grid.best_params_}")

print("\n⏳ Running GridSearchCV for XGBoost...")
xgb_param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 6],
    'learning_rate': [0.05, 0.1]
}
xgb_grid = GridSearchCV(
    XGBClassifier(eval_metric='mlogloss', random_state=42, use_label_encoder=False),
    xgb_param_grid, cv=3, scoring='accuracy', n_jobs=-1, verbose=0
)
xgb_grid.fit(X_train, y_train)
print(f"  Best XGB params: {xgb_grid.best_params_}")

# ── Define Final Models ───────────────────────────────────────────────────────
models = {
    'Random Forest': rf_grid.best_estimator_,
    'SVM':           SVC(kernel='rbf', probability=True, random_state=42),
    'XGBoost':       xgb_grid.best_estimator_,
    'MLP':           MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=300, random_state=42)
}

# Pre-fit SVM and MLP (they weren't tuned via GridSearch)
for name in ['SVM', 'MLP']:
    models[name].fit(X_train, y_train)

print("\n✅ All models trained.")

"""### 3.2 — Model Evaluation: Classification Reports & Confusion Matrices"""

results = {}
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for name, model in models.items():
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)

    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob, multi_class='ovr')
    cv_scores = cross_val_score(model, X_scaled, y, cv=skf, scoring='accuracy')

    results[name] = {
        'Accuracy':  round(acc, 4),
        'ROC-AUC':   round(auc, 4),
        'CV Mean':   round(cv_scores.mean(), 4),
        'CV Std':    round(cv_scores.std(), 4)
    }

    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"  Accuracy: {acc:.4f}  |  ROC-AUC: {auc:.4f}  |  5-Fold CV: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
    print(classification_report(y_test, y_pred, target_names=['Low', 'Medium', 'High']))

    # Confusion matrix
    disp = ConfusionMatrixDisplay(
        confusion_matrix(y_test, y_pred),
        display_labels=['Low', 'Medium', 'High']
    )
    fig, ax = plt.subplots(figsize=(5, 4))
    disp.plot(ax=ax, colorbar=False, cmap='Blues')
    ax.set_title(f'Confusion Matrix — {name}', fontsize=12)
    plt.tight_layout()
    plt.savefig(f'/content/drive/MyDrive/cm_{name.replace(" ", "_")}.png', dpi=150)
    plt.show()

"""### 3.3 — ROC Curves (One-vs-Rest, All Models)"""

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

# Binarize labels for OvR ROC plotting
y_test_bin = label_binarize(y_test, classes=[0, 1, 2])
class_names = ['Low Risk', 'Medium Risk', 'High Risk']
colors_roc  = ['#2ecc71', '#f39c12', '#e74c3c']

fig, axes = plt.subplots(1, 4, figsize=(20, 5), sharey=True)
fig.suptitle('ROC Curves — One-vs-Rest (All Models)', fontsize=14)

for ax, (name, model) in zip(axes, models.items()):
    y_score = model.predict_proba(X_test)
    for cls_idx, (cls_name, color) in enumerate(zip(class_names, colors_roc)):
        fpr, tpr, _ = roc_curve(y_test_bin[:, cls_idx], y_score[:, cls_idx])
        roc_auc = auc(fpr, tpr)
        ax.plot(fpr, tpr, color=color, lw=2,
                label=f'{cls_name} (AUC={roc_auc:.2f})')
    ax.plot([0, 1], [0, 1], 'k--', lw=1)
    ax.set_title(name, fontsize=11)
    ax.set_xlabel('False Positive Rate')
    ax.set_xlim([0, 1])
    ax.set_ylim([0, 1.02])
    ax.legend(loc='lower right', fontsize=7)

axes[0].set_ylabel('True Positive Rate')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/roc_curves_all_models.png', dpi=150)
plt.show()
print("✅ ROC curves saved.")

"""### 3.4 — Model Comparison Summary & Best Model Selection"""

results_df = pd.DataFrame(results).T
results_df = results_df.sort_values('Accuracy', ascending=False)

print("=" * 60)
print("  MODEL COMPARISON SUMMARY (sorted by Accuracy)")
print("=" * 60)
print(results_df.to_string())
print("=" * 60)

# Bar chart comparison
ax = results_df[['Accuracy', 'ROC-AUC', 'CV Mean']].plot(
    kind='bar', figsize=(10, 5), colormap='Set2', edgecolor='white'
)
plt.title('Model Comparison — Accuracy, ROC-AUC, 5-Fold CV Mean', fontsize=13)
plt.ylabel('Score')
plt.ylim(0.5, 1.0)
plt.xticks(rotation=20, ha='right')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/model_comparison.png', dpi=150)
plt.show()

# Select best model
best_model_name = results_df['Accuracy'].idxmax()
best_model = models[best_model_name]
print(f"\n🏆 Best Model: {best_model_name}")
print(f"   Accuracy : {results_df.loc[best_model_name, 'Accuracy']}")
print(f"   ROC-AUC  : {results_df.loc[best_model_name, 'ROC-AUC']}")
print(f"   5-Fold CV: {results_df.loc[best_model_name, 'CV Mean']} ± {results_df.loc[best_model_name, 'CV Std']}")

"""---
## Module 4: SHAP Explainability & Model Persistence
**Responsible:** M. Khizar Akram (02-131232-064) — Team Lead

This module handles:
1. SHAP-based global feature importance explanation for the best model
2. SHAP summary plot (bar chart) for interpretability
3. Saving the trained model, scaler, and encoders to Google Drive

### 4.1 — SHAP Feature Importance Explanation
"""

import shap
import pickle
import matplotlib.pyplot as plt
import numpy as np

print(f"Computing SHAP values for: {best_model_name}")

# Use a background sample for efficiency
background = shap.sample(X_train, 100, random_state=42)

# Use TreeExplainer for tree-based models, KernelExplainer for others
if best_model_name in ['Random Forest', 'XGBoost']:
    explainer = shap.TreeExplainer(best_model)
    shap_values = explainer.shap_values(X_test[:500])
else:
    explainer = shap.KernelExplainer(best_model.predict_proba, background)
    shap_values = explainer.shap_values(X_test[:100])

# For multi-class: shap_values is a list (one array per class)
# We'll use class 2 (High Risk) as it's the most clinically important
if isinstance(shap_values, list):
    shap_vals_high = shap_values[2]
else:
    # In some versions/models, SHAP returns a 3D array [samples, features, classes]
    if len(shap_values.shape) == 3:
        shap_vals_high = shap_values[:, :, 2]
    else:
        shap_vals_high = shap_values

# ── SHAP Summary Bar Chart ────────────────────────────────────────────────────
plt.figure(figsize=(9, 6))
# Fixing the 'str' object is not callable error by providing a specific color
# and ensuring plot_type is correctly handled.
shap.summary_plot(
    shap_vals_high,
    features=X_test[:shap_vals_high.shape[0]],
    feature_names=feature_names,
    plot_type='bar',
    show=False,
    color="#e74c3c"
)
plt.title(f'SHAP Feature Importance — {best_model_name} (High Risk Class)', fontsize=13)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/shap_importance.png', dpi=150)
plt.show()
print("✅ SHAP bar chart saved.")

# ── SHAP Beeswarm (Full Detail) ───────────────────────────────────────────────
plt.figure(figsize=(9, 6))
shap.summary_plot(
    shap_vals_high,
    features=X_test[:shap_vals_high.shape[0]],
    feature_names=feature_names,
    show=False
)
plt.title(f'SHAP Beeswarm — {best_model_name} (High Risk Class)', fontsize=13)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/shap_beeswarm.png', dpi=150)
plt.show()
print("✅ SHAP beeswarm chart saved.")

"""### 4.2 — Save Best Model to Google Drive"""

import pickle

with open('/content/drive/MyDrive/best_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

with open('/content/drive/MyDrive/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

with open('/content/drive/MyDrive/feature_names.pkl', 'wb') as f:
    pickle.dump(feature_names, f)

with open('/content/drive/MyDrive/encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)

print(f"✅ Best model ({best_model_name}) saved to Google Drive.")
print("✅ Scaler, feature names, and encoders saved.")
print("\nFiles saved:")
print("  /content/drive/MyDrive/best_model.pkl")
print("  /content/drive/MyDrive/scaler.pkl")
print("  /content/drive/MyDrive/feature_names.pkl")
print("  /content/drive/MyDrive/encoders.pkl")

"""---
## Module 4 (Continued): Gradio App Deployment
**Responsible:** M. Khizar Akram (02-131232-064) — Team Lead

This module handles:
1. Building the Gradio web interface for live student risk prediction
2. SHAP-based per-prediction explanation displayed inline
3. Logging every prediction to a persistent Google Drive CSV file
4. Launching with `share=True` to generate a public shareable URL

### 4.3 — Gradio Risk Prediction App (with Prediction Logger)
"""

import gradio as gr
import pickle
import csv
import shap
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import io
import os
from datetime import datetime
from PIL import Image

# ── Load Artifacts ──
with open('/content/drive/MyDrive/best_model.pkl', 'rb') as f:
    model = pickle.load(f)
with open('/content/drive/MyDrive/scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
with open('/content/drive/MyDrive/feature_names.pkl', 'rb') as f:
    feature_names = pickle.load(f)
with open('/content/drive/MyDrive/encoders.pkl', 'rb') as f:
    encoders = pickle.load(f)

log_path = '/content/drive/MyDrive/prediction_log.csv'
if not os.path.exists(log_path):
    with open(log_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Timestamp','Gender','Age','CGPA','Academic Pressure',
                         'Study Satisfaction','Work/Study Hours','Sleep Duration',
                         'Dietary Habits','Financial Stress','Family History',
                         'Suicidal Thoughts','Risk Level','Confidence'])

# ── Initialize Explainer ──
# We use TreeExplainer for the Random Forest model
shap_explainer = shap.TreeExplainer(model)

def predict_risk(gender, age, academic_pressure, cgpa,
                 study_satisfaction, sleep_duration, dietary_habits,
                 work_study_hours, financial_stress,
                 family_history, suicidal_thoughts):

    gender_enc   = encoders['Gender'].transform([gender])[0]
    sleep_enc    = encoders['Sleep Duration'].transform([sleep_duration])[0]
    diet_enc     = encoders['Dietary Habits'].transform([dietary_habits])[0]
    family_enc   = encoders['Family History of Mental Illness'].transform([family_history])[0]
    suicidal_enc = encoders['Have you ever had suicidal thoughts ?'].transform([suicidal_thoughts])[0]

    input_data   = np.array([[gender_enc, age, academic_pressure, cgpa,
                               study_satisfaction, sleep_enc, diet_enc,
                               work_study_hours, financial_stress,
                               family_enc, suicidal_enc]])
    input_scaled = scaler.transform(input_data)
    prediction   = int(model.predict(input_scaled)[0])
    probs        = model.predict_proba(input_scaled)[0]

    labels = {0: "✅ Low Risk", 1: "✒  Medium Risk", 2: "❌ High Risk"}
    advice = {
        0: "You seem to be in a healthy zone. Keep up the good habits!",
        1: "Moderate risk detected. Consider speaking with a faculty advisor or counselor.",
        2: "High risk detected. Please reach out to your university counselor as soon as possible."
    }

    result     = labels[prediction]
    confidence = f"{max(probs) * 100:.1f}%"
    message    = advice[prediction]

    # Log entry
    with open(log_path, 'a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow([datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                         gender, age, cgpa, academic_pressure, study_satisfaction,
                         work_study_hours, sleep_duration, dietary_habits,
                         financial_stress, family_history, suicidal_thoughts,
                         result, confidence])

    # Generate SHAP Plot
    shap_img = None
    try:
        # Generate SHAP values for the specific input
        shap_values = shap_explainer.shap_values(input_scaled)

        # Handle multi-class output (list of arrays for RF)
        if isinstance(shap_values, list):
            sv_row = shap_values[prediction][0]
        else:
            # Some versions return [samples, features, classes]
            if len(shap_values.shape) == 3:
                sv_row = shap_values[0, :, prediction]
            else:
                sv_row = shap_values[0]

        sorted_idx   = np.argsort(np.abs(sv_row))
        sorted_vals  = sv_row[sorted_idx]
        sorted_feats = [feature_names[i] for i in sorted_idx]
        bar_colors   = ['#e74c3c' if v > 0 else '#3498db' for v in sorted_vals]

        fig, ax = plt.subplots(figsize=(8, 5))
        bars = ax.barh(sorted_feats, sorted_vals, color=bar_colors, edgecolor='none', height=0.6)
        ax.axvline(0, color='black', linewidth=0.8, linestyle='--', alpha=0.4)
        ax.set_xlabel('SHAP Value (Higher = Increases predicted risk)', fontsize=9)
        ax.set_title(f"Why the model predicted: {result}", fontsize=11)

        plt.tight_layout()
        buf = io.BytesIO()
        plt.savefig(buf, format='png', dpi=130)
        buf.seek(0)
        shap_img = Image.open(buf).copy()
        plt.close(fig)
        buf.close()
    except Exception as e:
        print(f"SHAP visualization error: {e}")

    return result, confidence, message, shap_img

with gr.Blocks(title="BUKC Student Risk Predictor") as app:
    gr.Markdown("# ✅ Student Academic Risk Predictor")
    with gr.Row():
        gender = gr.Radio(["Male", "Female"], label="Gender", value="Male")
        age    = gr.Slider(17, 30, value=20, step=1, label="Age")
    with gr.Row():
        cgpa              = gr.Slider(0.0, 4.0, value=2.5, step=0.1, label="CGPA (0.0 – 4.0)")
        academic_pressure = gr.Slider(1, 5, value=3, step=1, label="Academic Pressure (1-5)")
    with gr.Row():
        study_satisfaction = gr.Slider(1, 5, value=3, step=1, label="Study Satisfaction (1–5)")
        work_study_hours   = gr.Slider(0, 12, value=6, step=1, label="Work/Study Hours per Day")
    with gr.Row():
        sleep_duration = gr.Dropdown(["Less than 5 hours", "5-6 hours", "7-8 hours", "More than 8 hours"], value="7-8 hours", label="Sleep Duration")
        dietary_habits = gr.Dropdown(["Healthy", "Moderate", "Unhealthy"], value="Moderate", label="Dietary Habits")
    with gr.Row():
        financial_stress  = gr.Slider(1, 5, value=2, step=1, label="Financial Stress (1–5)")
        family_history    = gr.Radio(["Yes", "No"], label="Family History of Mental Illness", value="No")
        suicidal_thoughts = gr.Radio(["Yes", "No"], label="Ever had Suicidal Thoughts?", value="No")

    btn = gr.Button("✅ Predict Risk", variant="primary")

    with gr.Row():
        risk_out = gr.Textbox(label="Risk Level", interactive=False)
        conf_out = gr.Textbox(label="Confidence", interactive=False)
    advice_out = gr.Textbox(label="Recommendation", interactive=False)
    shap_out   = gr.Image(label="Feature Contributions", type="pil", interactive=False)

    btn.click(fn=predict_risk, inputs=[gender, age, academic_pressure, cgpa, study_satisfaction, sleep_duration, dietary_habits, work_study_hours, financial_stress, family_history, suicidal_thoughts], outputs=[risk_out, conf_out, advice_out, shap_out])

app.launch(share=True)